[32m2024-09-26 12:17:45 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ab45162d-7383-4b37-b5f2-06a1ed70a8c4 - 62334 - LOGS_CAPTURED - Started capturing logs in process (pid: 62334).
[32m2024-09-26 12:17:45 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ab45162d-7383-4b37-b5f2-06a1ed70a8c4 - 62334 - players_file - STEP_START - Started execution of step "players_file".
[32m2024-09-26 12:17:51 -0600[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ab45162d-7383-4b37-b5f2-06a1ed70a8c4 - 62334 - players_file - STEP_OUTPUT - Yielded output "result" of type "DataFrame". Warning! Type check failed.
[32m2024-09-26 12:17:51 -0600[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - ab45162d-7383-4b37-b5f2-06a1ed70a8c4 - 62334 - players_file - STEP_FAILURE - Execution of step "players_file" failed.

dagster._core.errors.DagsterTypeCheckDidNotPass: Type check failed for step output "result" - expected type "DataFrame". Description: Value of type <class 'NoneType'> failed type check for Dagster type DataFrame, expected value to be of Python type pandas.core.frame.DataFrame.

Stack Trace:
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 506, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 550, in _type_check_and_store_output
    for output_event in _type_check_output(step_context, step_output_handle, output):
  File "/opt/anaconda3/envs/nba-project/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 424, in _type_check_output
    raise DagsterTypeCheckDidNotPass(
[0m
